spring:
  application:
    name: patient-service
  datasource:
    url: jdbc:postgresql://103.174.103.250:5432/ayurveda_db?currentSchema=public
    username: ayurveda
    password: "S@b8at1zeauyrveda"
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-init-sql: SET search_path TO public
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: public
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    table: flyway_schema_history_patient
    schemas: public
    default-schema: public

server:
  port: 8081

springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true
  show-actuator: false

logging:
  level:
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
